// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/radio-player/AmbientCard.tsx": () => import("../components/mockups/radio-player/AmbientCard.tsx"),
  "./components/mockups/radio-player/Current.tsx": () => import("../components/mockups/radio-player/Current.tsx"),
  "./components/mockups/radio-player/DJConsole.tsx": () => import("../components/mockups/radio-player/DJConsole.tsx"),
  "./components/mockups/radio-player/TVMode.tsx": () => import("../components/mockups/radio-player/TVMode.tsx"),
  "./components/mockups/radio-player/TimelineSchedule.tsx": () => import("../components/mockups/radio-player/TimelineSchedule.tsx")
};
